### ISSUE TITLE
 What is the four images downloaded used for? 

### ISSUE THREAD

**Issue by ytf4425** [lstprjct/IDM-Activation-Script#11]
The script download four files and I can not understand what it is used for.

```powershell
set link=https://www.internetdownloadmanager.com/images/idm_box_min.png
call :download
set link=https://www.internetdownloadmanager.com/register/IDMlib/images/idman_logos.png
call :download

:: it may take some time to reflect registry keys.
timeout /t 3 >nul

set foundkeys=
call :action
if [%foundkeys%] GEQ [7] goto _skip

set link=https://www.internetdownloadmanager.com/pictures/idm_about.png
call :download
set link=https://www.internetdownloadmanager.com/languages/indian.png
call :download
```

**Comment by ali-farhad** [comment]
it forces IDM to download these files thereby forcing it to create certain keys in window's registry that the script is expecting in certain locations.

**Comment by ytf4425** [comment]
but

> it forces IDM to download these files thereby forcing it to create certain keys in window's registry that the script is expecting in certain locations.

but why need four files rather than one?

**Comment by lstprjct** [comment]
> > it forces IDM to download these files thereby forcing it to create certain keys in window's registry that the script is expecting in certain locations.
> 
> but why need four files rather than one?

These files are downloaded to create Windows registry key which the script will intercept and use the info to add the registration key and freeze it so idm can't write those keys. If idm rewrite those keys, your license will become invalid.
