### ISSUE TITLE
I'M CAROUSE IF THIS SCRIPT IS SAFE TO RUN (ANY HELP)

### ISSUE THREAD

**Issue by Elmehdioub** [lstprjct/IDM-Activation-Script#17]
IS IT SAFE WHY FOR A SIMPLE ACTIVATION HAD TO USE SO MUCH CODE FEELS LIKE IT DOES MORE THAN ACTIVATING IDM, ANYONE CAN UNDERSTAND WHAT IN THAT CODE ?

**Comment by Scarlaid** [comment]
it does, dont worry

**Comment by Elmehdioub** [comment]
Aw, thanks
