### ISSUE TITLE
新版本

### ISSUE THREAD

**Issue by dghgw2022** [lstprjct/IDM-Activation-Script#18]
新的版本激活不了,会提示无效的注册码

**Comment by lstprjct** [comment]
> 新的版本激活不了,会提示无效的注册码

![IMG-20240120-WA0005](https://github.com/lstprjct/IDM-Activation-Script/assets/88411318/6139a063-1b54-4cf4-89c4-349c4aae5aaf)
works fine for latest version!

**Comment by dfmjndm** [comment]
In the latest version, 6.42, IDM will check the validity of the activation code online when creating a download task. In my environment, it was initially activated successfully, but after several download tasks, the software will warn you that this is an invalid activation code and then prompt you to purchase an official activation code through a pop-up window.

**Comment by YYH2913** [comment]
The same problem in 6.42, but it seems that it can be resolved by reactivating

**Comment by yinyihui1995** [comment]
<img width="346" alt="PixPin_2024-02-08_23-19-56" src="https://github.com/lstprjct/IDM-Activation-Script/assets/32058165/c805b7f0-7dc0-4cec-bd3f-120f5df97f4e">

6.42 build 3
I'm having the same problem, a window pops up after the download.

**Comment by dfmjndm** [comment]
> The same problem in 6.42, but it seems that it can be resolved by reactivating

Reactivate cannot solve the problem, after an hour, the software reminded me again that it has expired.

**Comment by sfovnsfojvn** [comment]
> > The same problem in 6.42, but it seems that it can be resolved by reactivating
> 
> Reactivate cannot solve the problem, after an hour, the software reminded me again that it has expired.

Me either in 6.42, Reactivate doesn't work.

**Comment by so1ve** [comment]
+1 for reopen this issue.

**Comment by hyy34** [comment]
6.42 bulid3 ，No longer activated

**Comment by dghgw2022** [comment]
已经不能再激活了
