### ISSUE TITLE
output wrong

### ISSUE THREAD

**Issue by FuSiYu666** [lstprjct/IDM-Activation-Script#19]
'�▄▀██▄█░░░▌' is not recognized as an internal or external command,
operable program or batch file.
           ▐░░░▀████▀▄░░░▌       ◇────────────────────◇
'�▄▄▄▄▄▄▄▄▀═' is not recognized as an internal or external command,
operable program or batch file.

          Create By Piash
          _____________________________________________

          [1] Activate IDM
          [2] Reset IDM Activation / Trial in Registry
          _____________________________________________

          [3] Toggle Windows Firewall  [Enabled]
          _____________________________________________

          [4] ReadMe
          [5] Homepage
          [6] Exit
       ___________________________________________________

        Enter a menu option in the Keyboard [1,2,3,4,5,6]

**Comment by lstprjct** [comment]
I removed that bug character and roll backed to old simple style.
