### ISSUE TITLE
don't really know why people use this

### ISSUE THREAD

**Issue by bruh-person** [lstprjct/IDM-Activation-Script#2]
i dont really know why people use this, you can make up your activation info and use serial FOX6H-3KWH4-7TSIN-Q4US7, which this script uses.

**Comment by AmirulAndalib** [comment]
![alt text](https://en.meming.world/images/en/8/8e/All_Right_Then%2C_Keep_Your_Secrets.jpg)

**Comment by matt873** [comment]
> 

Can you share the exact steps to do it manually?
