### ISSUE TITLE
What a hell is this

### ISSUE THREAD

**Issue by gd-cho** [lstprjct/IDM-Activation-Script#22]
![image](https://github.com/lstprjct/IDM-Activation-Script/assets/75920170/4068d579-8b14-4243-bd74-766417f415ad)

**Comment by xygkevin** [comment]
同样遇到了这个问题

**Comment by wisdomgo** [comment]
When I use it,I'll also meeting this plight now.

**Comment by yinyihui1995** [comment]
暂时只能用最新脚本里的 Freeze Trial 来解决，For now, we can only use the ‘Freeze Trial’ from the latest script to resolve it.

**Comment by svilme** [comment]
I have the same problem too.

**Comment by XCQ0607** [comment]
这样成功使用了Freeze Trial吗？每次打开软件都弹出这个。
Did this successfully use Freeze Trial? This pops up every time I open the software.
![5270decf-a898-496b-872b-f18b33c481b5](https://github.com/lstprjct/IDM-Activation-Script/assets/125746521/ec890d86-9cde-4177-b05a-c917bf327c9b)
