### ISSUE TITLE
seems that  the script not work for the latest idm

### ISSUE THREAD

**Issue by ntbowen** [lstprjct/IDM-Activation-Script#5]
I installed the latest version IDM from https://mirror2.internetdownloadmanager.com/idman641build14.exe?v=lt&filename=idman641build14.exe and run the script but failed.

**Comment by vavavr00m** [comment]
@ntbowen For me, the license still works even after updating. I also uninstalled the license and relicensed, still works. What's the error message? Is it a fresh install of IDM? Did you run it from PowerShell?

**Comment by lstprjct** [comment]
> I installed the latest version IDM from https://mirror2.internetdownloadmanager.com/idman641build14.exe?v=lt&filename=idman641build14.exe and run the script but failed.

Follow the step correctly, this script Still works perfectly Even on the latest idm build.
